// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyhuzusqgwcoplhlynmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5aHV6dXNxZ3djb3BsaGx5bm1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwODk2OTAsImV4cCI6MjA2MTY2NTY5MH0.39JcSC4MCQRNjOC13BKBFRqKdztd6DA9yGXRkaWJ2MY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);